name: CLI CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Run tests
      run: bin/qmk pytest
