name: PR Lint keyboards

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Print info
      run: |
        git rev-parse --short HEAD

    - name: Run qmk info
      shell: 'bash {0}'
      run: |
        QMK_KEYBOARDS=$(qmk list-keyboards)

        exit_code=0
        for KB in $QMK_KEYBOARDS; do
          echo "linting ${KB}"
          qmk info -kb ${KB} 2>&1 | tee /tmp/$$
          !(grep -cq ☒ /tmp/$$)
          : $((exit_code = $exit_code + $?))
        done
        exit $exit_code
